### ISSUE TITLE
Folder Icons

### ISSUE THREAD

**Issue by TryTryAgain** [AnderWeb/android_packages_apps_Launcher#11]
Issue:
Cannot change the icon of the folders on the desktop.

I do know dxTop allows you to change them, and was wondering if this has been thought about.

Not sure if you consider requests = issues, and I apologize if I am coming off as a jerk asking for it in this way; but, I have looked around and couldn't find anything on the web. I do admit I did not try asking in any IRC channels.

Thanks.

**Comment by Macrophage001** [comment]
You could make a metamorph of the icons you want to use?
