### ISSUE TITLE
Froyo permissions weirdness...?

### ISSUE THREAD

**Issue by AnderWeb** [AnderWeb/android_packages_apps_Launcher#14]
On the AVD with froyo (since first froyo sdk release, including the latest update) i get a lot of warning messages like this one:

<pre>
Not granting permission android.permission.BIND_APPWIDGET to package xxxxxx
</pre>

What scares me more is that there's a lot of this ones too:

<pre>
W/PackageManager(   81): Unknown permission com.google.android.googleapps.permission.GOOGLE_AUTH.mail in package com.android.contacts
W/PackageManager(   81): Unknown permission android.permission.ADD_SYSTEM_SERVICE in package com.android.phone
W/PackageManager(   81): Not granting permission android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS to package com.android.browser (protectionLevel=2 flags=0x1be45)
</pre>

And a few more, but related to gapps (and as they're missing from avd, i don't know if they're relevant).

I've received a few logcats from users with issues regarding widgets not updating, and maybe this could be the cause?

**Comment by AnderWeb** [comment]
Reading /data/system/packages.xml shows the launcher permissions, and the BIND_APPWIDGET permission is NOT there....

So may we suppose FROYO is forbidding any other app from using widgets??? WTF??

**Comment by boombuler** [comment]
you can ignore this permission! it is only needed by the app widget picker!

**Comment by AnderWeb** [comment]
Yeah, i know, forgot to close it
