### ISSUE TITLE
Drawer and ABs are not accessible via trackball

### ISSUE THREAD

**Issue by JakeWharton** [AnderWeb/android_packages_apps_Launcher#15]
While not a show-stopper, I find myself sometimes one-handing the phone with the trackball and it would be nice to access the drawer and LAB/RAB. The stock 2.2 launcher included this functionality if memory serves.

The drawer icon is able to be highlighted but depressing the trackball does not open it. The ABs are not even able to be highlighted.

**Comment by AnderWeb** [comment]
Thanks,
I have some code not uploaded yet with some fixes for this so expect it to be resolved soon :-)

**Comment by JakeWharton** [comment]
Thank you, this has been fixed. However, you can not scroll and select apps in the drawer with the trackball when it was opened with the trackball.

**Comment by AnderWeb** [comment]
Oh, you're right!!!
I'll try to fix as soon as possible, but i'm on a 10days holidays so... :(

**Comment by AnderWeb** [comment]
Forgot to close this, fixed since 1.0

**Comment by JakeWharton** [comment]
Yeah but what about my comment above? You still cannot scroll in the drawer with the trackball after opening via the trackball? I'm on 1.01.

I tried investigating the source for the cause but I'm buried in my own project right now. If you can't get to it (as it's so minor and a huge edge case) I'll get around to it eventually.

**Comment by AnderWeb** [comment]
Oh, sorry, I've fixed that today, just not uploaded.
 If you check it on landscape mode, you'll see that it properly works, was just a missing line in the portrait xml.
