### ISSUE TITLE
Settings layout file

### ISSUE THREAD

**Issue by hdlopes** [AnderWeb/android_packages_apps_Launcher#2]
Hi,

I think the file res/xml/launcher_settings.xml should be moved to res/layout/launcher_settings.xml. As I can see from other projects the xml directory contains other data used by the application.

I think only line 27 from the file src/com/android/launcher/MyLauncherSettings.java needs to be changed,

addPreferencesFromResource(R.xml.launcher_settings);

replacing .xml with .layout.

I'm not doing this myself because I can't build the code.

**Comment by AnderWeb** [comment]
Actually you could put the xml on any place you want... but on android API Demos (http://developer.android.com/intl/de/resources/samples/ApiDemos/res/xml/preferences.html) they store them inside "res/xml", so i did the same :)
