### ISSUE TITLE
An option to stop the hiding of dock/status bar?

### ISSUE THREAD

**Issue by rogerchucker** [AnderWeb/android_packages_apps_Launcher#20]
Hi, this is a feature request and I know this will be downgraded to the lowest importance but I'll still try :) I was wondering if an option can be adding in the ADW Launcher settings to disable hiding of the status bar as well as the dock on the bottom as result of sliding on the homescreen (where there's no app icon). It happened a couple of times by accident sliding and I was wondering if an option to prevent that could be doable by some simple code addition/changes. Thanks a bunch for the hard work.

**Comment by AnderWeb** [comment]
Those are not bugs (and there are already options for them).
The customizable swipe actions show/hide the status bar. You can configure them.

the app drawer button opens the "dockbar", a hidden toolbar to place unlimited icons by drag and drop. (and while it's visible, the regular buttons aren't).
 you can hide it again by dragging it down fast or just disable it in settings.

**Comment by rogerchucker** [comment]
Thanks for that little trick! I didn't know you could place icons there if the dock disappears. I certainly didn't mean to allude to this issue as a bug - I just thought mabe there should be an option to turn that off. But thanks for the directions.
