### ISSUE TITLE
keyboard/dock autorotation

### ISSUE THREAD

**Issue by gazpachoking** [AnderWeb/android_packages_apps_Launcher#22]
The recent change to force a home orientation (AnderWeb@3222612634981d432d0d) removes the ability to just have the homescreen rotate on keyboard extension or dock insertion. Formerly, just unchecking the 'orientation sensor' option still allowed these rotations, however new portrait mode does not. Can such a mode be added to the home orientation menu?

**Comment by AnderWeb** [comment]
Don't enable the persistence option and leave the orientation set to auto, that should work.

**Comment by gazpachoking** [comment]
Yes, but that also leaves the gravity sensor active...  (btw, I don't want the sensor disabled globally, just for the launcher)

**Comment by AnderWeb** [comment]
You're right, I'll see what I can do :)

**Comment by gazpachoking** [comment]
Sounds good, thanks!

**Comment by AnderWeb** [comment]
I think this is fixed on 1.1.0. (if you don't enable persistence mode)

**Comment by gazpachoking** [comment]
Just grabbed 1.1.1 from the market and all looks good, thanks!
