### ISSUE TITLE
AllAppsSlidingView bug

### ISSUE THREAD

**Issue by leiyuanhua** [AnderWeb/android_packages_apps_Launcher#24]

**Comment by AnderWeb** [comment]
?

**Comment by leiyuanhua** [comment]
when click the HandleView to open the AllAppsSlidingView,the application icon display confusion

**Comment by AnderWeb** [comment]
Your message displays confision to me :S
I don't understand anything

**Comment by leiyuanhua** [comment]
can you give me a email,I will send you a picture

**Comment by leiyuanhua** [comment]
我在使用ADW Launcher时遇到下面一个问题：

点击mHandleView显示所有应用程序：
if (allAppsOpen) {
closeAllApps(true);
} else {
showAllApps(true);
}
假设每一屏显示16个应用程序，总共有2屏。
有时候点击mHandleView显示所有应用程序：

会出现第一屏显示后三列，第二屏显示前1列情况。
请问要怎样修改才能整屏显示即要么显示第一屏，要么显示第二屏？

**Comment by leiyuanhua** [comment]
My English is poor. I described the problem once again.
During the scrolling，Careless click one application's icon so start the application,when you enter the AllAppsSlidingView again,the application's icon display confusion.

**Comment by leiyuanhua** [comment]
fixed this problem:
AllAppsSlidingView->
public void open(boolean animate) {->
            if(mBlockLayouts){
                snapToDestination();//add 
                holder.open(animate, mAnimationDuration);

**Comment by AnderWeb** [comment]
Thanks!, I understand the problem now ;-)

**Comment by AnderWeb** [comment]
Little tweak for the drawer opening/closing animation conditions.
Also little change to center the current screen on opening the horizontal drawer
Closed by 07e169159740180a904135db081f1266e030b4a6
