### ISSUE TITLE
Very long load time with many apps installed

### ISSUE THREAD

**Issue by mugendai** [AnderWeb/android_packages_apps_Launcher#41]
This is the second of two related issues I am putting in.

The first issue concerned the time it takes before ADW displays any icons on the homescreens(caused by the number of icons ADW must load)

This second issue is about the time it takes from when ADW first displays homescreen icons, till it becomes fully usable(stops lagging)

If many apps are installed, ADW can take several seconds(as much as 10 for me) after showing icons before it is fully usable.  While it may be somewhat responsive, meaning I can swipe on the homescreen and it may switch after a few seconds, or I can tap an icon and it may start to load after a few seconds, ADW does not become smooth and fully responsive until all apps have been loaded in to the app list.

With many apps installed, it can take a long time to load all of the apps in to the app list(drawer).

I believe that is an app cache, that stores the list of apps, and their icons were used, that this long load time could be severely shortened, and make a tremendous impact on the performance of ADW for many android users.

Again, I point to FolderOrganizer which seems to have an app cache, as I can always quickly load it, and select my apps.

FolderOrganizer takes a while the very first time it loads to read through all installed apps, but, subsequent launches(unless you clear it's data) do not take any time at all to load the app list.  It also seems to be able to keep up with the changes in apps as I install/uninstall apps.

I think using similar methodology to cache the app list for ADW is completely feasible, and I must beg of you to make this a priority.

I am telling you, this will resolve so many peoples issues with their android phones, it is not even funny.

All of my testing has been done on the Motorola Droid 1.  I've tested with a range of OS versions, and am currently running a CM6 Nightly.

Thank you.

**Comment by AnderWeb** [comment]
Please, would you mind adding those issues into the official issue tracker?
The github issue tracker is rarely used by "the users" so we made one here http://code.google.com/p/adw-launcher-android/issues/list

Thanks
