### ISSUE TITLE
DesktopIndicator  display error

### ISSUE THREAD

**Issue by leiyuanhua** [AnderWeb/android_packages_apps_Launcher#45]
when you change the phone's screen orientation,For example:portrait to landscape,the portrait screen desktop indicator does not disappear, leading to landscape screen desktop indicator shows overlap.

**Comment by leiyuanhua** [comment]
I fixed the error as follow:
DesktopIndicator.java->
    public void hide() {
        // TODO Auto-generated method stub
                mIndicator.setVisibility(View.INVISIBLE);
        setVisibility(View.INVISIBLE);
    }

```
public void show() {
    // TODO Auto-generated method stub
    if(mVisibleTime<0){
        setVisibility(View.VISIBLE);
                    mIndicator.setVisibility(View.VISIBLE);
    }
}
```

**Comment by AnderWeb** [comment]
Properly Closed by bb28ebdda843a7e88532b0f744248bcd78773be0

**Comment by leiyuanhua** [comment]
can you tell me the different between this two modify?

**Comment by AnderWeb** [comment]
Your solution breaks the indicator if autohide is set to true

**Comment by leiyuanhua** [comment]
thanks!
