### ISSUE TITLE
[improvement] Add margin to each page

### ISSUE THREAD

**Issue by walkingice** [AnderWeb/android_packages_apps_Launcher#7]
First at all, thanks for the amazing Launcher. It becomes my favorite launcher since I saw it two days ago.

I think if ADW Launcher adds some margin to each pages of AllApps, that would improve user experience very much. (please see http://picasaweb.google.com/walkingice0204/Blog#5484209822477766434)

There are two patches which let user could add arbitrary margin (0px ~ 75px) to each page. Hope it helps.

http://0xlab.org/~walkingice/0001-Add-Margin-into-each-pages-of-AllAppsSlidingView.patch
http://0xlab.org/~walkingice/0002-New-option-to-tweak-page-margin.patch

**Comment by AnderWeb** [comment]
That's great!
I'm going to make a release today, but tomorrow i'll be merging this and playing with the code.

**Comment by AnderWeb** [comment]
Merged onto my main 3 branches, thanks!!!

**Comment by walkingice** [comment]
got it, thanks!
