### ISSUE TITLE
Text fade in transition to app drawer pops in instead

### ISSUE THREAD

**Issue by dyndragon** [AnderWeb/android_packages_apps_Launcher#9]
The text for the apps on the fade in transition to the app drawer does not actually fade in even when the option is turned on. The text always "pops" in.

**Comment by AnderWeb** [comment]
Thanks!!! This way i won't forget :-)

**Comment by AnderWeb** [comment]
Fixed de app-drawer labels not really fading...
Closed by 6155aa8695e4629fd19dc35979bc52777ec5f6a8
